---

# - name: Install Gallaxy Collections
#   shell: ansible-galaxy collection install community.general

- name: Install postgresql
  apt: pkg=postgresql state=present force=yes

- name: Start postgresql server
  service: name=postgresql state=started enabled=yes

# Posgres pg_hba
- name: Sets postgres pg_hba.conf file
  template:
    src: "pg_hba.conf.j2"
    dest: "/etc/postgresql/10/main/pg_hba.conf"
    mode: 0644
  notify: Restart Postgres

- name: Configure global settings.
  lineinfile:
    dest: "/etc/postgresql/10/main/postgresql.conf"
    regexp: "^#?listen_addresses"
    line: listen_addresses  '*'
    state: present
    mode: 0644
  notify: Restart Postgres

# Postgres Init Script
- name: Sets postgres initfile
  template:
    src: "init_postgresql.sh.j2"
    dest: "/tmp/init_postgresql.sh"
    mode: 0755

- name: Configure max connections.
  lineinfile:
    dest: "/etc/postgresql/10/main/postgresql.conf"
    regexp: "max_connections"
    line: max_connections = 600
    state: present
    mode: 0644
  notify: Restart Postgres

# - name: Add a auth method
#   lineinfile:
#     path: /etc/postgresql/10/main/pg_hba.conf
#     line: host    all         all         0.0.0.0/0             password
#   notify: Restart Postgres

- name: Run a script
  script: /tmp/init_postgresql.sh
