

- name: Installing Maven
  apt: name=maven state=present update_cache=yes

- name: install Perl_dep
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'gcc', 'make', 'libexpat1-dev']

- name: Installing
  command: cpan App::cpanminus

- name: Set mode +x to PerlModule Script
  file:
    path: ~/ansible/roles/build_dep/files/perl_lib.sh
    mode: 0755

- name: create directory for project
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
  loop:
    - ~/git
    - ~/.intermine

- name: Set mode +x to StartUp Script
  file:
    path: ~/ansible/roles/build_dep/files/startup.sh
    mode: 0755

- name: deploy testmine.properties files
  template: src=biotestmine.properties.j2 dest=/tmp/biotestmine.properties

- name: Move testmine.properties to a proper destination
  shell: mv /tmp/biotestmine.properties ~/.intermine

- name: Copy and Execute the script
  script: ./roles/build_dep/files/startup.sh


# - name: Copy and Execute the script
#   script: ./roles/build_dep/files/perl_lib.sh
